### ISSUE TITLE
Error in Worksheet2 screenshots?

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/scratch-olympics-hurdler#3]
I'm afraid I haven't actually tried following the worksheets myself in Scratch, but looking at the two screenshots in the HIDING THE HURDLES section, they seem to be set up with the `if distance > 160` as the outer-most `if` block, with all other code nested inside. Doesn't this mean that *none* of the code in those scripts will be executed until the `distance > 160`?
I suspect that what was intended was for the second `if` block in each of the scripts to be placed *under* the `if distance > 160` block, rather than *inside* it?

**Comment by lurch** [comment]
i.e. using the code inside the comment-section on the page, and adding python-style indentation, the `images/hurdles2.png` currently shows:
```scratch
when green flag clicked
show
go to x: [230] y:[-77]
forever
    if <(distance) > [160]>
        hide
        if <(speed) > [1]>
            change x by [-10]
            wait <[1]/(speed)> secs
            if <(x position) < [-230]>
                go to x:[230] y:[-77]
```
whereas I suspect it's *supposed* to show:
```scratch
when green flag clicked
show
go to x: [230] y:[-77]
forever
    if <(distance) > [160]>
        hide
    if <(speed) > [1]>
        change x by [-10]
        wait <[1]/(speed)> secs
        if <(x position) < [-230]>
            go to x:[230] y:[-77]
```
(and similarly for `images/collide2.png`).

**Comment by MarcScott** [comment]
Thanks @lurch - I've been using http://scratchblocks.github.io/ and it's suddenly very easy to introduce logical errors.

**Comment by lurch** [comment]
I'm not sure if it was intentional, but it looks like you've added a new `#worksheet2.md#` file (and `.#worksheet2.md`), rather than editing the existing `worksheet2.md` file??

I hadn't come across scratchblocks before - very neat :)

**Comment by lurch** [comment]
...and looking at "Breaking the finish line" section, I wonder if the 'switch costume to finishline' should actually be _between_ 'when green flag clicked' and 'forever'? (instead of inside 'forever' as it is now)

**Comment by MarcScott** [comment]
That's just Emacs saving temp files. The original worksheets didn't change
as it was just image corrections.
