### ISSUE TITLE
Broken image on raspberrypi.org

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/scratch-olympics-hurdler#4]
Not quite sure what's gone wrong here... https://github.com/raspberrypilearning/scratch-olympics-hurdler/blob/master/worksheet2.md displays all the images okay, but on https://www.raspberrypi.org/learning/scratch-olympics-hurdler/worksheet2/ the second image in the SETTING UP THE START section just appears as `![script](images/run4.png)`

Ping @bennuttall in case it's a problem with the copy-resources-to-the-website script.

**Comment by bennuttall** [comment]
Thanks. Fixed.

Looks like it doesn't like indentation at the end of a list.

**Comment by lurch** [comment]
... and yet `start1.png` just a few lines earlier seems to work okay with indentation? \*shrug\*

**Comment by bennuttall** [comment]
`start1.png` is in between list items. `run4.png` is after the final list item, so it's outside the `<ol>`. Images in between list items need to be indented to prevent breaking the list numbering.

**Comment by lurch** [comment]
Ahhh. In that case, how come `finish3.png` works okay? ;)

(I'm not being deliberately awkward, I'm just trying to understand if we can prevent issues like this happening again)

**Comment by bennuttall** [comment]
My guess is because it's preceded by that commented out code block?
